---
# tasks file for roles/database
- name: Run postgres
  docker_container:
    name: postgres
    image: pierrektl/postgres:postgres
    env: 
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'usr'
      POSTGRES_PASSWORD: 'pwd'
