---
# tasks file for roles/database
- name: Run postgres
  docker_container:
    name: postgres
    image: pierrektl/tp1:postgres
    env: 
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: network_app
