- hosts: all
  gather_facts: false
  become: yes
  # Install Docker
  tasks:
  - name: Install docker
    import_role:
     name: docker
  - name: Create database
    import_role:
     name: postgres
  - name: Create app
    import_role:
     name: back-api
  - name: Create httpd
    import_role:
     name: httpd
  - name: Create network
    import_role:
     name: network
