- hosts: all
  gather_facts: false
  become: yes
  # Install Docker
  tasks:
  - name: Install docker
    import_role:
     name: docker
  - name: Create network
    import_role:
     name: network
  - name: Create database
    import_role:
     name: database
  - name: Create app
    import_role:
     name: app
  - name: Create httpd
    import_role:
     name: proxy
